{% set name = "tfcausalimpact" %}
{% set version = "0.0.18" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/WillianFuks/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 3e2c588b2bac36557c9b2aefd30c15e0e2ccfa4609828b47c70612a4b5632490

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0
  skip: True  # [py>312]

requirements:
  host:
    - pip
    - python
    - setuptools
    - wheel
    - isort
    - flake8
  run:
    - python
    - jinja2
    - pandas >=1.3.5,<=2.2
    - tensorflow >=2.10
    - tensorflow-probability >=0.18,<=0.25
    # tensorflow-probability[tf]
    - tf-keras >=2.16
    - matplotlib-base

test:
  files:
    - tests
  source_files:
    - tests
  imports:
    - causalimpact
    - causalimpact.__version__
    - causalimpact.data
    - causalimpact.inferences
    - causalimpact.main
    - causalimpact.misc
    - causalimpact.model
    - causalimpact.plot
    - causalimpact.summary
  commands:
    - python -c "import keras._tf_keras.keras.backend as K; print('Keras backend=', K.backend())"
    # Skip pip check on Windows due to conda/pip metadata conflict:
    # tf-keras conda package references pip tensorflow dependency but we have conda tensorflow
    - pip check  # [not win]
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    - pytest -v tests
    # llm testing
    - pytest -v tests/llm_tests.py
  requires:
    - pip
    - pytest
    - mock
    # TensorFlow has a dependency on Keras. Keras >3 can use different backends like PyTorch or TensorFlow.
    # For some reason, on CI macOS, PyTorch is selected as the default backend,
    # and testing 'causalimpact' imports cause a missing PyTorch dependency error.
    # Setting the KERAS_BACKEND=tensorflow doesn't help
    - pytorch  # [osx]

about:
  home: https://github.com/WillianFuks/tfcausalimpact
  summary: Google's Causal Impact Algorithm Implemented on Top of TensorFlow Probability.
  description: Google's Causal Impact Algorithm Implemented on Top of TensorFlow Probability.
    The algorithm basically fits a Bayesian structural model on past observed data to make
    predictions on what future data would look like. Past data comprises everything that
    happened before an intervention (which usually is the changing of a variable as being
    present or not, such as a marketing campaign that starts to run at a given point).
    It then compares the counter-factual (predicted) series against what was really
    observed in order to extract statistical conclusions.
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  doc_url: https://github.com/WillianFuks/tfcausalimpact/blob/master/README.md
  dev_url: https://github.com/WillianFuks/tfcausalimpact

extra:
  recipe-maintainers:
    - thewchan
  skip-lints:
    - missing_pip_check  # [win]
    - missing_imports_or_run_test_py  # [osx]